### ISSUE TITLE
Undefined method `bytesize` error when attempting to run get_torrents_status

### ISSUE THREAD

**Issue by tprepper** [t3hk0d3/deluge-api#8]
Attempting to get torrents' status using this method (from the README):
`client.core.get_torrents_status({}, ['name', 'hash'])`
returns this error:
```
#<NoMethodError: undefined method `bytesize' for ["6ebb0596f16e8dca6635921c5e125f293e4cecad", {"name"=>"archlinux-2023.03.01-x86_64.iso", "hash"=>"6ebb0596f16e8dca6635921c5e125f293e4cecad"}]:Array>
```

**Comment by t3hk0d3** [comment]
Do you have full stack trace?
What is your Ruby version?

Can you try with latest released version 0.2.2?

**Comment by tprepper** [comment]
Ruby version:
`ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]`
the full error:
```
2023-03-06 14:03:14 +0100 Read: #<NoMethodError: undefined method `bytesize' for ["6ebb0596f16e8dca6635921c5e125f293e4cecad", {"name"=>"archlinux-2023.03.01-x86_64.iso", "hash"=>"6ebb0596f16e8dca6635921c5e125f293e4cecad"}]:Array>
```
still does this with deluge-rpc 0.2.2

**Comment by tprepper** [comment]
Oh - I don't think this is an issue, actually. Whoops. It seems like outputting it with "puts" does work properly, as I assume is intended.
